version: '3.8'

services:
  public-tender-analysis-dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8050:8050"
    environment:
      HOST: 0.0.0.0
      PORT: 8050
      PYTHONUNBUFFERED: 1  # Ensures logs are streamed immediately
    volumes:
      - .:/app  # Mounts the current directory to the container's working directory
