vendors_to_exclude = [
    'Three separate companies',
    'Various Vendors',
    '2 Different Companies',
    '2 vendors',
    '3 separate companies',
    'bid was split between 3 contractors',
    'Bidding Options 3 successful companies split the contract',
    'Multiple Vendors',
    'No bids - award - vendor chosen',
    'There are multiple vendors',
    'There were 4 vendors who submitted low bids',
    'Awarded to more than one vendor. See details below.',
    'Awarded To Multiple Vendors',
    'Awarded to sixteen different vendors',
    'Awarded to Various Suppliers (See Below)',
    'Awarded to vendors below',
    '21 Vendors added to exisiting Standing Offer List',
    '3 contactors were awarded parts of this bid',
    '30 separate bidders split this contract',
    '4 Different Bidders',
    'Awarded Low-Bid - See list of venders below',
    'Awarded to all Bidders',
    'Four bidders won a portion of this tender. See memorandum.',
    '0',

]